meta:
  config_version: 3
  client_id: zebra-day
  database_name: zebra-day
  owner_repo_name: zebra-day
  domain_code: Z
  domain_registry_path: ~/.config/tapdb/domain_code_registry.json
  prefix_registry_path: ~/.config/tapdb/prefix_ownership_registry.json
environments:
  dev:
    domain_code: Z
    engine_type: local
    host: localhost
    port: '5544'
    ui_port: '8118'
    database: zebra_day_dev
    audit_log_euid_prefix: ZGX
    support_email: support@lsmc.bio
    cognito_user_pool_id: ''
  prod:
    domain_code: Z
    engine_type: aurora
    host: zebra-day.cluster-REPLACE.us-west-2.rds.amazonaws.com
    port: '5432'
    user: tapdb_admin
    password: ''
    database: zebra_day_prod
    audit_log_euid_prefix: ZGX
    support_email: support@lsmc.bio
    cognito_user_pool_id: ''
    region: us-west-2
    cluster_identifier: zebra-day
    iam_auth: 'true'
    ssl: 'true'
